apiVersion : apps/v1
kind: Deployment
metadata:
  name: import-for-sa 
spec:
  replicas: 1
  template:
    spec:
        tolerations:
        - key: "taint-test"
          operator: "Equal"
          value: "taint-value"
          effect: "NoSchedule"
      containers:
        - name: import-for-sa 
          command: ["java","-jar","/app.jar"]
          args: ["--spring.config.location=file:/config/application.yml"]
          volumeMounts:
          - mountPath: /mnt/import-for-sa
            name: import-for-sa-volume
            readOnly: false
            subPath: import-for-sa
          - mountPath: /config
            name: application-properties
            readOnly: true
                          
      volumes:
      - name: import-for-sa-volume
        persistentVolumeClaim:
          claimName: import-for-sa-pvc
      - name: application-properties
        configMap:
          name: import-for-sa-configmap
          items:
            - key: application.yml
              path: application.yml
          defaultMode: 420
