configMapGenerator:
- files:
  - application.yml
  name: import-for-sa-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ce82257991acr.azurecr.io/import-for-sa
  newTag: "lastest"
